<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.547">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chialing Sung">
<meta name="dcterms.date" content="2025-04-10">

<title>Module 05: Lab 02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="lab08-Chialing Sung_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab08-Chialing Sung_files/libs/quarto-html/quarto.js"></script>
<script src="lab08-Chialing Sung_files/libs/quarto-html/popper.min.js"></script>
<script src="lab08-Chialing Sung_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab08-Chialing Sung_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab08-Chialing Sung_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab08-Chialing Sung_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab08-Chialing Sung_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab08-Chialing Sung_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab08-Chialing Sung_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">1</span> Load the Dataset</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2</span> Feature Engineering</a></li>
  <li><a href="#traintest-split" id="toc-traintest-split" class="nav-link" data-scroll-target="#traintest-split"><span class="header-section-number">3</span> Train/Test Split</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">4</span> Linear Regression</a>
  <ul class="collapse">
  <li><a href="#generalized-linear-regression-summary" id="toc-generalized-linear-regression-summary" class="nav-link" data-scroll-target="#generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</a></li>
  </ul></li>
  <li><a href="#diagnostic-plot" id="toc-diagnostic-plot" class="nav-link" data-scroll-target="#diagnostic-plot"><span class="header-section-number">5</span> Diagnostic Plot</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation"><span class="header-section-number">6</span> Evaluation</a>
  <ul class="collapse">
  <li><a href="#model-evaluation-plot" id="toc-model-evaluation-plot" class="nav-link" data-scroll-target="#model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</a></li>
  </ul></li>
  <li><a href="#submission" id="toc-submission" class="nav-link" data-scroll-target="#submission">Submission</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 05: Lab 02</h1>
<p class="subtitle lead">Regression Modeling on Employment Data</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chialing Sung </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 10, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 9, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="objectives" class="level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<ol type="1">
<li>Use <strong>PySpark</strong> to process the Lightcast dataset.</li>
<li>Engineer features from structured columns for salary prediction.</li>
<li>Train <strong>Linear Regression model</strong>.</li>
<li>Evaluate models using <strong>RMSE</strong> and <strong>R²</strong>.</li>
<li>Visualize predictions using diagnostic plots.</li>
<li>Push work to GitHub and submit the repository link.</li>
</ol>
</section>
<section id="setup" class="level1 unnumbered">
<h1 class="unnumbered">Setup</h1>
<p>The instruction below provides you with general keywords for columns used in the lightcast file. See the data schema generated after the load dataset code above to use proper column name. For visualizations, tables, or summaries, please <strong>customize colors, fonts, and styles</strong> as appropriate to avoid a <strong>2.5-point deduction</strong>. Also, <strong>provide a two-sentence explanation</strong> describing key insights drawn from each section’s code and outputs.</p>
<ol type="1">
<li>Follow the steps below as necessary, use your best judgement in importing/installing/creating/saving files as needed.</li>
<li>Create a new Jupyter Notebook in your <code>ad688-sp25-lab08</code> directory named <code>lab08_yourname.ipynb</code>, if the file exists make sure to change the name.</li>
<li>Use your <strong>EC2 instance</strong> for this lab.</li>
<li>Ensure the <code>lightcast_data.csv</code> file is available on the EC2 instance. if not then <strong>Download the dataset</strong></li>
<li><strong>Add the dataset to <code>.gitignore</code></strong> to avoid pushing large files to GitHub. Open your <code>.gitignore</code> file and add:</li>
<li>Make sure to create a virtual environment and install the required Python libraries if needed, don’t forget to activate it:</li>
<li>Install the required Python libraries if needed, you can also use the given requirement file to install the packages to the virtual environment:</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gdown</span> https://drive.google.com/uc<span class="pp">?</span>id=1V2GCHGt2dkFGqVBeoUFckU4IhUgk4ocQ</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"lightcast_job_postings.csv"</span> <span class="op">&gt;&gt;</span> .gitignore</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="load-the-dataset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Load the Dataset</h1>
<ol type="1">
<li><strong>Load the Raw Dataset</strong>:
<ul>
<li>Use Pyspark to the <code>lightcast_data.csv</code> file into a DataFrame:</li>
<li>You can reuse the previous code.</li>
<li><span class="uured-bold">Copying code from your friend constitutes plagiarism. DO NOT DO THIS</span>.</li>
</ul></li>
</ol>
<div id="cell-3" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.io <span class="im">as</span> pio</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pio.renderers.default <span class="op">=</span> <span class="st">"notebook"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Spark Session</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(<span class="st">"LightcastData"</span>).getOrCreate()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>) <span class="op">\</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    .option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>) <span class="op">\</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    .option(<span class="st">"multiLine"</span>, <span class="st">"true"</span>) <span class="op">\</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    .option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>) <span class="op">\</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    .csv(<span class="st">"lightcast_job_postings.csv"</span>) </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Show Schema and Sample Data</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"---This is Diagnostic check, No need to print it in the final doc---"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">#df.printSchema() </span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#df.show(5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 68:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>---This is Diagnostic check, No need to print it in the final doc---</code></pre>
</div>
</div>
</section>
<section id="feature-engineering" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Feature Engineering</h1>
<p>Feature Engineering is a crucial step in preparing your data for machine learning. In this lab, we will focus on the following tasks:</p>
<ol type="1">
<li><strong>Drop rows with missing values</strong> in the target variable and key features.</li>
<li>By now you are already familiar with the code and the data. Based on your understanding please choose any 3 (my code output has 10) variables as:
<ol type="1">
<li>two continuous variables (use your best judgment!)</li>
<li>one categorical.</li>
<li>Your dependent variable (y) is <code>SALARY</code>.</li>
</ol></li>
<li><strong>Convert categorical variables</strong> into numerical representations using <strong>StringIndexer</strong> and <strong>OneHotEncoder</strong>.</li>
<li><strong>Assemble features</strong> into a single vector using <strong>VectorAssembler</strong>.</li>
<li><strong>Split the data</strong> into training and testing sets.</li>
</ol>
<div id="cell-5" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Drop rows with nulls in selected columns</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>selected_columns <span class="op">=</span> [<span class="st">"SALARY"</span>, <span class="st">"MIN_YEARS_EXPERIENCE"</span>, <span class="st">"MODELED_DURATION"</span>, <span class="st">"REMOTE_TYPE_NAME"</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df.dropna(subset<span class="op">=</span>selected_columns)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, OneHotEncoder</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Encode the categorical variable</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>indexer <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_NAME"</span>, outputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_INDEX"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>encoder <span class="op">=</span> OneHotEncoder(inputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_INDEX"</span>, outputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_VEC"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> VectorAssembler</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Assemble features</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>[<span class="st">"MIN_YEARS_EXPERIENCE"</span>, <span class="st">"MODELED_DURATION"</span>, <span class="st">"REMOTE_TYPE_VEC"</span>],</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pipeline for transformation</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>[indexer, encoder, assembler])</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply pipeline</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>df_transformed <span class="op">=</span> pipeline.fit(df_clean).transform(df_clean)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Show example</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>df_transformed.select(<span class="st">"SALARY"</span>, <span class="st">"features"</span>).show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Split the data</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>train_data, test_data <span class="op">=</span> df_transformed.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+------+-----------------------+
|SALARY|features               |
+------+-----------------------+
|107645|(5,[0,1],[10.0,41.0])  |
|192800|[6.0,55.0,1.0,0.0,0.0] |
|125900|[12.0,18.0,1.0,0.0,0.0]|
|170000|[6.0,55.0,1.0,0.0,0.0] |
|118560|[5.0,20.0,0.0,1.0,0.0] |
+------+-----------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
</section>
<section id="traintest-split" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Train/Test Split</h1>
<ul>
<li>Perform a <strong>random split</strong> of the data into training and testing sets.</li>
<li>Set a random seed for reproducibility.</li>
<li>You can choose a number for splitting to your liking, justify your choice.</li>
</ul>
<div id="cell-7" class="cell" data-execution_count="29">
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                [Stage 79:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(13883, 2)
(2957, 2)</code></pre>
</div>
</div>
<p>This section performs feature engineering by converting a categorical column (REMOTE_TYPE_NAME) into numerical vectors using StringIndexer and OneHotEncoder, then combines it with two continuous features using VectorAssembler. The resulting dataset is randomly split into training (82%) and testing (18%) sets, producing 13,883 and 2,957 records respectively, ensuring reproducibility with a fixed seed.</p>
</section>
<section id="linear-regression" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Linear Regression</h1>
<ul>
<li>Train a <strong>Linear Regression</strong> model using the training data. <span class="uured-bold">You will run in to an important issue here. Please make an effort in figuring it by yourself. This is one of the most asked interview questions in CapitalOne’s management recruiting program.</span></li>
<li>Evaluate the model on the test data.</li>
<li>Print the coefficients, intercept, R², RMSE, and MAE.</li>
<li>Use the <code>summary</code> object to extract the coefficients and their standard errors, t-values, and p-values.</li>
<li>Create a DataFrame to display the coefficients, standard errors, t-values, p-values, and confidence intervals.</li>
<li>Interpret the coefficients and their significance and explain the model performance metrics.</li>
</ul>
<div id="cell-10" class="cell" data-execution_count="30">
<div class="cell-output cell-output-stderr">
<pre><code>25/04/08 15:17:47 WARN Instrumentation: [ecb78f29] regParam is zero, which might cause numerical instability and overfitting.
[Stage 84:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Model Evaluation ---
R²: 0.2615575507291191
RMSE: 35999.18812167445
MAE: 27899.407417659335

--- Coefficient Details ---
Intercept: 73373.22535886645
Length of coefficients: 5
Length of SE: 6
Length of t-values: 6
Length of p-values: 6</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std Error</th>
<th data-quarto-table-cell-role="th">t-Value</th>
<th data-quarto-table-cell-role="th">p-Value</th>
<th data-quarto-table-cell-role="th">95% CI Lower</th>
<th data-quarto-table-cell-role="th">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>6659.755167</td>
<td>94.179172</td>
<td>70.713673</td>
<td>0.000000e+00</td>
<td>6475.163990</td>
<td>6844.346344</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>45.357254</td>
<td>24.130591</td>
<td>1.879658</td>
<td>6.017567e-02</td>
<td>-1.938705</td>
<td>92.653213</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>9069.765706</td>
<td>2449.144855</td>
<td>3.703238</td>
<td>2.136903e-04</td>
<td>4269.441791</td>
<td>13870.089621</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10906.975945</td>
<td>2507.076173</td>
<td>4.350476</td>
<td>1.368122e-05</td>
<td>5993.106645</td>
<td>15820.845244</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>20633.854374</td>
<td>2985.498687</td>
<td>6.911359</td>
<td>5.009770e-12</td>
<td>14782.276948</td>
<td>26485.431799</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This section fits a Linear Regression model to the training data and evaluates it using R² (0.26), RMSE (≈36,000), and MAE (≈28,899), indicating moderate predictive performance with room for improvement. The table displays coefficient estimates along with their standard errors, t-values, p-values, and confidence intervals—showing that most features are statistically significant (p &lt; 0.05), especially Feature_0, Feature_2, Feature_3, and Feature_4.</p>
<section id="generalized-linear-regression-summary" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</h2>
<p>The summary of the Generalized Linear Regression model provides important insights into the model’s performance and the significance of each feature. The coefficients indicate the relationship between each feature and the target variable (salary), while the standard errors, t-values, and p-values help assess the reliability of these estimates.</p>
<ul>
<li>Please interpret them in the context of your data and model.</li>
<li>Feature Names are purposefully not printed in the output. You can use the <code>features</code> variable to print them out.</li>
</ul>
<div id="cell-13" class="cell" data-execution_count="31">
<div class="cell-output cell-output-stderr">
<pre><code>25/04/08 15:18:12 WARN Instrumentation: [76407da5] regParam is zero, which might cause numerical instability and overfitting.
[Stage 86:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+---+-----------+--------------------+--------------------+--------------------+------------------------+---------------------+--------------------+
|   |  Feature  |      Estimate      |     Std Error      |      t-Value       |        p-Value         |    95% CI Lower     |    95% CI Upper    |
+---+-----------+--------------------+--------------------+--------------------+------------------------+---------------------+--------------------+
| 0 | Feature_0 | 6659.7551670608755 | 94.17917189740737  | 70.71367302226417  |          0.0           |  6475.163990141957  | 6844.346343979794  |
| 1 | Feature_1 | 45.35725381762988  | 24.130591213065223 | 1.8796577927635578 |  0.06017566579323552   | -1.9387049599779544 | 92.65321259523772  |
| 2 | Feature_2 | 9069.765706342789  | 2449.1448546066526 | 3.703237760430241  | 0.00021369031103035674 | 4269.4417913137495  | 13870.089621371828 |
| 3 | Feature_3 | 10906.975944737305 | 2507.0761730991476 | 4.350476488017728  | 1.368121891354157e-05  |  5993.106645462976  | 15820.845244011634 |
| 4 | Feature_4 | 20633.854373743186 | 2985.4986865606998 | 6.911359387504346  | 5.009770376318556e-12  | 14782.276948084214  | 26485.43179940216  |
+---+-----------+--------------------+--------------------+--------------------+------------------------+---------------------+--------------------+</code></pre>
</div>
</div>
<p>This section fits a Generalized Linear Regression model using a Gaussian family and identity link, then prints coefficient estimates, standard errors, t-values, p-values, and confidence intervals. From the top features shown, most coefficients (e.g., Feature_0, Feature_2, Feature_3, and Feature_4) are statistically significant (p-value &lt; 0.05), indicating a strong relationship with the target variable SALARY.</p>
</section>
</section>
<section id="diagnostic-plot" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Diagnostic Plot</h1>
<p>Diagnostic plots are essential for evaluating the performance of regression models. In this section, we will create several diagnostic plots to assess the linear regression model’s assumptions and performance. There are four (2*2 grid) main plots we will create, you can use <code>seaborn</code> or <code>matplotlib</code> for this:</p>
<ol type="1">
<li><strong>Predicted vs Actual Plot</strong></li>
<li><strong>Residuals vs Predicted Plot</strong></li>
<li><strong>Histogram of Residuals</strong></li>
<li><strong>QQ Plot of Residuals</strong></li>
</ol>
<div id="cell-16" class="cell" data-execution_count="35">
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-Chialing%20Sung_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The diagnostic plots indicate some deviation from normality and heteroscedasticity. The Q-Q plot shows moderate departure from the normal line in the tails, and both the Residuals vs Fitted and Scale-Location plots reveal non-constant variance, suggesting potential issues with linearity or missing variables.</p>
</section>
<section id="evaluation" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Evaluation</h1>
<p>The evaluation of the model is crucial to understand its performance. In this section, we will calculate and visualize the following metrics: 1. <strong>R² (Coefficient of Determination)</strong>: Indicates how well the model explains the variance in the target variable. 2. <strong>RMSE (Root Mean Squared Error)</strong>: Measures the average magnitude of the errors between predicted and actual values.</p>
<div id="cell-19" class="cell" data-execution_count="36">
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 110:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Model Evaluation ---
R²: 0.2616
RMSE: 35999.19
AIC: 331199.33
BIC: 62093.21</code></pre>
</div>
</div>
<p>R² (0.2616): About 26.16% of the variance in salary is explained by the model. This suggests a moderate fit, indicating there may still be unaccounted variability.</p>
<p>RMSE (35,999.19): The average prediction error is around $35,999, which indicates the typical deviation of predicted salaries from actual salaries.</p>
<p>AIC (331,199.33) and BIC (62,093.21): These are model selection criteria. While lower values are generally better, they are most useful when comparing multiple models.</p>
<section id="model-evaluation-plot" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</h2>
<ul>
<li>Display the predicted vs actual salary plot with a red line indicating the ideal fit (y=x).</li>
<li>Use <code>seaborn</code> or <code>matplotlib</code> to create the plot.</li>
<li>Customize the plot with appropriate titles, labels, and legends.</li>
<li>Describe the plot in a few sentences, highlighting key insights and observations.</li>
</ul>
<div id="cell-22" class="cell" data-execution_count="38">
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-Chialing%20Sung_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This scatter plot compares the predicted salary to the actual salary using the Generalized Linear Regression (GLR) model. The red diagonal line represents the ideal fit where predictions would perfectly match actual values (i.e., y = x).</p>
<p>Most points lie below the ideal line, indicating the model tends to underpredict salaries, especially at higher income levels. The R² value of 0.5073 suggests the model explains around 50.73% of the variance, showing moderate predictive power. The RMSE of 23,431 means the model’s predictions deviate by about $23K on average. The spread of points increases with salary, hinting at heteroscedasticity (non-constant variance), which may impact model reliability at higher salary ranges.</p>
</section>
</section>
<section id="submission" class="level1 unnumbered">
<h1 class="unnumbered">Submission</h1>
<ol type="1">
<li>Save figures in the <code>_output/</code> folder.</li>
<li>Commit and push code and output files:</li>
</ol>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> add .</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> commit <span class="at">-m</span> <span class="st">"Add Lab 08 Salary Prediction models and output"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> push origin main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="3" type="1">
<li>Submit your GitHub repository link.</li>
</ol>
</section>
<section id="resources" class="level1 unnumbered">
<h1 class="unnumbered">Resources</h1>
<ul>
<li><a href="https://spark.apache.org/docs/latest/ml-guide.html">PySpark MLlib Docs</a><br>
</li>
<li><a href="https://seaborn.pydata.org/">Seaborn Docs</a><br>
</li>
<li><a href="https://pandas.pydata.org/docs/user_guide/index.html">Pandas User Guide</a></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>